# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
    rust: "1.70"

python:
  install:
    - requirements: docs/requirements.txt
